### ISSUE TITLE
[bug] errorlog on screen event

### ISSUE THREAD

**Issue by asksven** [asksven/BetterWifiOnOff#67]
10-13 22:37:20.210 E/ActivityManager(2175):   0.8% 13329/com.asksven.betterwifionoff: 0.4% user + 0.4% kernel / faults: 914 minor
10-13 22:37:56.495 E/BetterWifiOnOff.WifiConnectedAlarmReceiver(14652): An error occured receiving the alarmConnectivityService: Neither user 10241 nor current process has android.permission.CHANGE_NETWORK_STATE.
10-13 22:39:20.140 E/SQLiteDatabase(13329): close() was never explicitly called on database '/data/data/com.asksven.betterwifionoff/databases/betterwifionoff' 
10-13 22:39:20.140 E/SQLiteDatabase(13329): at com.asksven.betterwifionoff.data.EventDBHelper.<init>(EventDBHelper.java:90)
10-13 22:39:20.140 E/SQLiteDatabase(13329): at com.asksven.betterwifionoff.data.EventDBHelper.getInstance(EventDBHelper.java:76)
10-13 22:39:20.140 E/SQLiteDatabase(13329): at com.asksven.betterwifionoff.data.EventLogger.addEvent(EventLogger.java:50)
10-13 22:39:20.140 E/SQLiteDatabase(13329): at com.asksven.betterwifionoff.data.EventLogger.addUserEvent(EventLogger.java:64)
10-13 22:39:20.140 E/SQLiteDatabase(13329): at com.asksven.betterwifionoff.handlers.ScreenEventHandler.onReceive(ScreenEventHandler.java:67)

**Comment by asksven** [comment]
Fixed, missing perm for route to host check (cage)
