### ISSUE TITLE
[bug] null pointer exception in 1.1 StringUtils

### ISSUE THREAD

**Issue by asksven** [asksven/BetterWifiOnOff#86]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x30000000 (has extras) } in com.asksven.betterwifionoff.handlers.ConnectionStatusHandler@4051eb48
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:722)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3683)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:633)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.asksven.android.common.utils.StringUtils.stripLeadingAndTrailingQuotes(StringUtils.java:108)
at com.asksven.betterwifionoff.utils.WifiControl.connectToBestNetwork(WifiControl.java:262)
at com.asksven.betterwifionoff.handlers.ConnectionStatusHandler.onReceive(ConnectionStatusHandler.java:84)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:709)
... 9 more

**Comment by asksven** [comment]
was fixed aready
