### ISSUE TITLE
[bug] null pointer exception in 1.1

### ISSUE THREAD

**Issue by asksven** [asksven/BetterWifiOnOff#87]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x8000010 (has extras) } in com.asksven.betterwifionoff.handlers.ConnectionStatusHandler@42a75cf0
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:765)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4918)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at com.asksven.betterwifionoff.utils.WifiControl.connectToBestNetwork(WifiControl.java:256)
at com.asksven.betterwifionoff.handlers.ConnectionStatusHandler.onReceive(ConnectionStatusHandler.java:84)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:755)

**Comment by asksven** [comment]
was fixed already
